name: food_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # icons and Image
  cupertino_icons: ^1.0.0
  
  # Animations and navigation
  eva_icons_flutter: ^2.0.1
  page_transition: ^1.1.7+5
  lottie: ^0.7.0+1
  
  # Firebase / 
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  # flutter_secure_storage: ^3.3.5
  flutter_secure_storage: ^3.3.3

  # Google locations
  google_maps_flutter: 1.0.10
  geocoder: ^0.2.1
  geolocator: ^6.1.6
  
  # Arcitecture
  provider: ^4.3.2+3


  # Assets 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/delivery_boy_bike_map.json 
